# Generated by Django 6.1 on 2026-08-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelport', '0002_alter_fuelprice_set_by_initializepaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='initializepaymentmethod',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'success'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='initializepaymentmethod',
            name='total_amount_to_pay',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='initializepaymentmethod',
            name='price_per_litre',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
